### ISSUE TITLE
TypeError: Cannot read property 'write' of undefined

### ISSUE THREAD

**Issue by alexdianomi** [interplanaria/bitbus#1]
I can't seen to find enough documentation about writing filters.

I want to run this filter:

{
  "bitbus": 1,
  "name": "md-feed-1",
  "from": 590470,
  "q": {
    "find": { "out.h1": "6d02" }
  }
}

But when I run bitbus start (after running bitbus new) I get this output:

bitbus start
BITBUS all finished at block undefined
/usr/local/lib/node_modules/bitbus/block.js:46
      fileStream.write("]")
                 ^

TypeError: Cannot read property 'write' of undefined
    at Stream.<anonymous> (/usr/local/lib/node_modules/bitbus/block.js:46:18)
    at Stream.emit (events.js:205:15)
    at Stream.stream.destroy (/usr/local/lib/node_modules/bitbus/node_modules/through/index.js:84:12)
    at _end (/usr/local/lib/node_modules/bitbus/node_modules/through/index.js:67:14)
    at Stream.stream.end (/usr/local/lib/node_modules/bitbus/node_modules/through/index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:44:10)
    at Stream.emit (events.js:205:15)
    at drain (/usr/local/lib/node_modules/bitbus/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/usr/local/lib/node_modules/bitbus/node_modules/through/index.js:45:5)
    at Stream.end (/usr/local/lib/node_modules/bitbus/node_modules/through/index.js:15:35)

Thanks very much

**Comment by alexdianomi** [comment]
Resolved: It was my fault not knowing the query syntax, but it would have been ideal if the app could have given an appropriate error at least.
