### ISSUE TITLE
Bug when using "project" to exclude fields

### ISSUE THREAD

**Issue by libitx** [interplanaria/bitbus#7]
In mongo, `project` can be used to either *include* specific fields or alternatively *exclude* specific fields. From the docs:

> If you specify the exclusion of a field or fields, all other fields are returned in the output documents.

## Recreate issue

Attempt the following query using bitbus:

```json
{
  "bitbus": 1,
  "name": "files",
  "from": 590000,
  "q": {
    "find": { "out.s1": "19HxigV4QyBv3tHpQVcUEQyq1pzZVdoAut" },
    "project": {
      "out.b2": 0,
      "out.h2": 0,
      "out.s2": 0,
      "out.lb2": 0,
      "out.lh2": 0,
      "out.ls2": 0
    }
  }
}
```

## Expected result

Bitbus should operate normally, outputting json data files with transactions excluding the `out.*2` fields.

## Actual result

Bitbus creates the output directory but crashes before writing any files. The following error is logged:

```console
/Users/whodis/.nvm/versions/node/v10.16.0/lib/node_modules/bitbus/block.js:32
    fileStream.write("]")
               ^

TypeError: Cannot read property 'write' of undefined
    at Stream.<anonymous> (/Users/whodis/.nvm/versions/node/v10.16.0/lib/node_modules/bitbus/block.js:32:16)
    at Stream.emit (events.js:203:15)
    at Stream.stream.destroy (/Users/whodis/.nvm/versions/node/v10.16.0/lib/node_modules/bitbus/node_modules/through/index.js:84:12)
    at _end (/Users/whodis/.nvm/versions/node/v10.16.0/lib/node_modules/bitbus/node_modules/through/index.js:67:14)
    at Stream.stream.end (/Users/whodis/.nvm/versions/node/v10.16.0/lib/node_modules/bitbus/node_modules/through/index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:42:10)
    at Stream.emit (events.js:203:15)
    at drain (/Users/whodis/.nvm/versions/node/v10.16.0/lib/node_modules/bitbus/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/Users/whodis/.nvm/versions/node/v10.16.0/lib/node_modules/bitbus/node_modules/through/index.js:45:5)
    at Stream.end (/Users/whodis/.nvm/versions/node/v10.16.0/lib/node_modules/bitbus/node_modules/through/index.js:15:35)
```

## Other notes

The above query works fine using a planaria API endpoint.
https://neongenesis.bitdb.network/query/1HcBPzWoKDL2FhCMbocQmLuFTYsiD73u1j/ewogICJ2IjogMywKICAicSI6IHsKICAgICJmaW5kIjogewogICAgICAib3V0LnMxIjogIjE5SHhpZ1Y0UXlCdjN0SHBRVmNVRVF5cTFwelpWZG9BdXQiCiAgICB9LAogICAgInByb2plY3QiOiB7CiAgICAgICJvdXQuYjIiOiAwLAogICAgICAib3V0LmgyIjogMCwKICAgICAgIm91dC5zMiI6IDAsCiAgICAgICJvdXQubGIyIjogMCwKICAgICAgIm91dC5saDIiOiAwLAogICAgICAib3V0LmxzMiI6IDAKICAgIH0sCiAgICAic29ydCI6IHsKICAgICAgImJsay5pIjogLTEsCiAgICAgICJpIjogLTEKICAgIH0sCiAgICAibGltaXQiOiAyMAogIH0KfQ==

When the `project` config is changed to **include** only the above fields, Bitbus works normally. The problems seems specifically related to *excluding* fields using Bitbus.

**Comment by Breavyn** [comment]
Although the crash will no longer occur because of cc453a860e068b75b1107de615bb93b383b2edf8 the problem with the query is due to incorrect handling by the bitbus.network planaria instance, for which AFAIK source code hasn't been released. There are other inconsistencies I've noticed between the mempool query's, which are filtered locally, and the crawl queries, filtered remotely.

**Comment by unwriter** [comment]
@Breavyn what was the inconsistency? Maybe I can take a look with more details.

**Comment by Breavyn** [comment]
I'd already forgotten specifically at the time, but I believe it was to do with hex encoded filters. Filtering with a hex field during the crawl phase would yield no results, but it would find transactions just fine in the mempool.
